version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory

      - run:
          name: Install last version Node.js
          command: 'sudo npm install -g npm@latest'

      - run:
          name: Install dependencies with NPM
          command: npm install

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run App
          command: npm start

workflows:
  version: 2
  Build and Test:
    jobs:
      - build